name: WGLC Issue
description: Working Group Last Call Issue
labels: [wglc, triage]
body:
  - type: markdown
    attributes:
      value: |
        Working Group Last Call (WGLC) is your opportunity to raise issues against the following drafts:

        * [A Vocabulary For Expressing AI Usage Preferences]()
        * [Associating AI Usage Preferences With Content]()

        This is a consensus call, which means that any matter not raised as an issue is presumed to have consensus.

        Please understand that:
        * Issues that are not within the scope of our charter will be closed without discussion.
        * Likewise, issues with the charter itself -- including whether the IETF should be doing this work -- will be closed without discussion. The appropriate time to discuss such things is during chartering.
        * Issues that have already been discussed have a presumption of consensus, but that will be confirmed if necessary. Genuinely new information is of greatest assistance when evaluating such issues.
        * Issues that have not yet been discussed will be evaluated on a case-by-case basis. Alternative approaches (e.g., "why didn't you do...") are presumed not to have consensus unless there is strong support for considering them.

  - type: checkboxes
    attributes:
      label: "Confirmation"
      description: "Before raising a Working Group Last Call issue, please confirm that:"
      options:
        - label: You have reviewed our [existing WLGC issues]() to assure that it is not already covered.
          required: true
        - label: You have read and understand the [IETF NOTE WELL](https://www.ietf.org/about/note-well/).
          required: true

  - type: textarea
    attributes:
      label: "Issue Description"
